version: "3.9"

services:
  db:
    image: postgres:16
    container_name: labiq_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - labiq_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: labiq_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: labiq_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  labiq_postgres_data: